
var db=null,currentUser=null,editing=null,editingSupplier=null,editingCliente=null,editingVeiculo=null;
var quotes={},cotacoes={},respostas={},suppliers={},fornecedores={},whatsappQueue={},purchaseOrders={},ordensCompra={},settings={},clientSetup={},priceDb={},robotStatus={},auditUnmatched={},oficinaClientes={},oficinaVeiculos={},draftItems=[];
var uiState={openPanels:{},selectedSuppliers:{}};
const ASSINATURA='Powered by thIAguinho Soluções Digitais';
const DEFAULT_MSG=`Olá {fornecedor}, aqui é {estabelecimento}.

Cotação {cotacao} - {veiculo} {placa}
Chassi: {chassi}
São {qtd} item(ns).

Confirme disponibilidade, marca, código da marca, descrição, preço atual e prazo pelo link:
{link}

{assinatura}`;
const NICHOS=[
['oficina','🔧','Autopeças / Oficina / Frota','Cotação de peças automotivas, OS, compra e lucro.'],
['construcao','🧱','Materiais de construção','Cimento, tubos, elétrica, hidráulica e acabamento.'],
['farmacia','💊','Farmácia / Drogaria','Produtos de giro, perfumaria e reposição.'],
['agro_pet','🐾','Agropecuária / Pet shop','Rações, sementes, ferramentas e insumos.'],
['informatica','💻','Informática / Eletrônicos','Peças, periféricos, manutenção e revenda.'],
['mercado','🛒','Mercado / Mercearia','Produtos de giro, bebidas, limpeza e frios.'],
['papelaria','📚','Papelaria / Escritório','Material escolar, escritório, toner e suprimentos.'],
['restaurante','🍽️','Restaurante / Food service','Alimentos, embalagens, bebidas e insumos.'],
['hotelaria','🏨','Hotel / Pousada','Enxoval, limpeza, manutenção e amenidades.'],
['estetica','💅','Estética / Salão / Barbearia','Cosméticos, equipamentos, descartáveis e reposição.'],
['marcenaria','🪵','Marcenaria / Móveis','Chapas, ferragens, cola, fita de borda e acessórios.'],
['ferragens','🔩','Ferragens / Metalúrgica','Parafusos, chapas, barras, ferramentas e EPI.'],
['eletricos','⚡','Elétrica / Iluminação','Cabos, disjuntores, lâmpadas, luminárias e quadros.'],
['hidraulica','🚰','Hidráulica / Piscina','Tubos, conexões, bombas, registros e produtos químicos.'],
['limpeza','🧼','Limpeza / Higiene','Químicos, descartáveis, papel, sacos e equipamentos.'],
['epi','🥽','Uniformes / EPI','Luvas, botas, capacetes, uniformes e sinalização.'],
['eventos','🎪','Eventos / Festas','Buffet, decoração, locação, som, iluminação e bebidas.'],
['clinicas','🦷','Clínicas / Odonto','Materiais clínicos, descartáveis, manutenção e limpeza.'],
['transportes','🚚','Transportes / Logística','Pneus, manutenção, peças, combustível e insumos.'],
['generico','🧾','Cotação genérica','Qualquer compra com fornecedores e comparação de preços.']
];
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function parseMoney(v){let s=String(v||'').replace(/[^\d,.-]/g,'').trim();if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');let n=Number(s);return Number.isFinite(n)?n:0}
function arrObj(o){return Object.entries(o||{}).map(([id,v])=>({id,...(v||{})}))}
function uid(p){return p+'_'+Date.now()+'_'+Math.random().toString(16).slice(2,8)}
function phoneBR(p){let d=String(p||'').replace(/\D/g,'');if(d.length===10||d.length===11)d='55'+d;return d}
function statusOpen(s){return ['open','aberta','aberto','enviada','importada','rascunho'].includes(String(s||'').toLowerCase())}
function applyTheme(t){document.body.classList.toggle('theme-dark',t==='dark');try{localStorage.setItem('valorIA_theme',t||'light')}catch(e){}}
function showTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tabpage').forEach(p=>p.classList.toggle('hidden',p.id!==id))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('loginBtn').onclick=()=>{const email=$('loginEmail').value.trim(),pass=$('loginPassword').value,err=$('loginError');err.textContent='';if(!email||!pass){err.textContent='Preencha e-mail e senha.';return}firebase.auth().signInWithEmailAndPassword(email,pass).catch(e=>err.textContent='Falha no login: '+(e.message||e.code))};
$('logoutBtn').onclick=()=>firebase.auth().signOut();$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
function init(){renderNiches();if(!window.firebaseConfig){alert('firebase-config.js não carregou.');return}if(!firebase.apps.length)firebase.initializeApp(window.firebaseConfig);firebase.auth().onAuthStateChanged(user=>{currentUser=user;$('loginOverlay').classList.toggle('authHidden',!!user);if(user&&!db)startApp()})}
function startApp(){db=firebase.database();db.ref('settings/main').on('value',s=>{settings=s.val()||{};fillSettings();renderAll()});db.ref('clientSetup').on('value',s=>{clientSetup=s.val()||{};fillClientSetup();renderAll()});db.ref('quotes').on('value',s=>{quotes=s.val()||{};renderAll()});db.ref('cotacoes').on('value',s=>{cotacoes=s.val()||{};renderAll()});db.ref('respostas').on('value',s=>{respostas=s.val()||{};renderAll()});db.ref('suppliers').on('value',s=>{suppliers=s.val()||{};renderAll()});db.ref('fornecedores').on('value',s=>{fornecedores=s.val()||{};renderAll()});db.ref('priceDb').on('value',s=>{priceDb=s.val()||{};renderAll()});db.ref('whatsappQueue').on('value',s=>{whatsappQueue=s.val()||{};renderAll()});db.ref('purchaseOrders').on('value',s=>{purchaseOrders=s.val()||{};renderAll()});db.ref('ordensCompra').on('value',s=>{ordensCompra=s.val()||{};renderAll()});db.ref('robotStatus/main').on('value',s=>{robotStatus=s.val()||{};renderAll()});db.ref('audit/unmatchedWhatsapp').on('value',s=>{auditUnmatched=s.val()||{};renderAll()});db.ref('oficina/clientes').on('value',s=>{oficinaClientes=s.val()||{};renderAll()});db.ref('oficina/veiculos').on('value',s=>{oficinaVeiculos=s.val()||{};renderAll()})}
function renderNiches(){$('setNiche').innerHTML=NICHOS.map(n=>`<option value="${n[0]}">${n[1]} ${n[2]}</option>`).join('');$('nicheList').innerHTML=NICHOS.map(n=>`<div class="nicheCard"><div class="nicheIcon">${n[1]}</div><div><b>${n[2]}</b><br><span class="muted small">${n[3]}</span><br><span class="pill">id: ${n[0]}</span></div></div>`).join('')}
function fillClientSetup(){if(document.activeElement&&String(document.activeElement.id||'').startsWith('client'))return;$('clientName').value=clientSetup.businessName||'';$('clientId').value=clientSetup.clientId||'';$('clientNiche').value=clientSetup.niche||'';$('clientSiteUrl').value=clientSetup.siteUrl||'';$('clientProjectId').value=clientSetup.projectId||'';$('clientDbUrl').value=clientSetup.databaseURL||'';$('clientAdminEmail').value=clientSetup.adminEmail||'';$('clientManagerPhone').value=clientSetup.managerPhone||'';$('clientCity').value=clientSetup.city||'';$('clientOwner').value=clientSetup.owner||'';$('clientStatus').value=clientSetup.status||'';$('clientObs').value=clientSetup.obs||''}
function saveClientSetup(){db.ref('clientSetup').update({businessName:$('clientName').value.trim(),clientId:$('clientId').value.trim(),niche:$('clientNiche').value.trim(),siteUrl:$('clientSiteUrl').value.trim(),projectId:$('clientProjectId').value.trim(),databaseURL:$('clientDbUrl').value.trim(),adminEmail:$('clientAdminEmail').value.trim(),managerPhone:$('clientManagerPhone').value.trim(),city:$('clientCity').value.trim(),owner:$('clientOwner').value.trim(),status:$('clientStatus').value.trim(),obs:$('clientObs').value.trim(),updatedAt:Date.now(),signature:ASSINATURA}).then(()=>alert('Dados do cliente salvos.'))}
function testFirebase(){alert(db?'Firebase conectado.':'Firebase não conectado.')}
function testAuth(){alert(currentUser?'Usuário logado: '+currentUser.email:'Sem usuário logado.')}
function copyPanelLink(){navigator.clipboard.writeText(location.origin+location.pathname).then(()=>alert('Link do painel copiado.'))}
function copyFornecedorLinkExample(){navigator.clipboard.writeText(location.origin+location.pathname.replace(/index.html.*$/,'')+'fornecedor.html').then(()=>alert('Link base do fornecedor copiado.'))}
function currentNiche(){return NICHOS.find(n=>n[0]===(settings.niche||'oficina'))||NICHOS[0]}
function fillSettings(){const n=currentNiche();$('brandIcon').textContent=settings.customIcon||n[1];$('brandTitle').textContent=(settings.name||'valor_IA')+' — Plataforma Profissional de Cotações';$('brandSubtitle').textContent=n[3];if(document.activeElement&&String(document.activeElement.id||'').startsWith('set'))return;$('setName').value=settings.name||settings.nome||'';$('setPhone').value=settings.phone||settings.whatsapp||'';$('setManagerPhone').value=settings.managerPhone||'';$('setCity').value=settings.city||'';$('setOwner').value=settings.owner||'';$('setNiche').value=settings.niche||'oficina';$('setTheme').value=settings.theme||localStorage.getItem('valorIA_theme')||'light';applyTheme($('setTheme').value);$('setIcon').value=settings.customIcon||'';$('setMessage').value=settings.messageTemplate||DEFAULT_MSG;$('setSignature').value=settings.signature||ASSINATURA}
function saveSettings(){db.ref('settings/main').update({name:$('setName').value.trim(),phone:$('setPhone').value.trim(),managerPhone:$('setManagerPhone').value.trim(),city:$('setCity').value.trim(),owner:$('setOwner').value.trim(),niche:$('setNiche').value,theme:$('setTheme').value,customIcon:$('setIcon').value.trim(),messageTemplate:$('setMessage').value.trim()||DEFAULT_MSG,signature:$('setSignature').value.trim()||ASSINATURA,updatedAt:Date.now()}).then(()=>{applyTheme($('setTheme').value);alert('Estabelecimento salvo.')})}
function supplierRows(){return[...arrObj(suppliers).map(s=>({...s,root:'suppliers',active:s.active!==false,name:s.name||s.nome,phone:s.phone||s.whatsapp,types:s.types||s.tipos||[]})),...arrObj(fornecedores).map(s=>({...s,root:'fornecedores',active:s.ativo!==false,name:s.nome||s.name,phone:s.whatsapp||s.phone,types:s.tipos||s.types||[]}))]}
function supplierName(id,q){if(suppliers[id])return suppliers[id].name||suppliers[id].nome||id;if(fornecedores[id])return fornecedores[id].nome||fornecedores[id].name||id;if(q&&q.raw&&q.raw.fornecedores&&q.raw.fornecedores[id])return q.raw.fornecedores[id].nome||id;return id||'Fornecedor'}
function clearSupplierForm(){editingSupplier=null;['supName','supPhone','supTypes','supObs'].forEach(i=>$(i).value='')}
function saveSupplier(){const data={name:$('supName').value.trim(),phone:phoneBR($('supPhone').value),types:$('supTypes').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),obs:$('supObs').value.trim(),active:true,updatedAt:Date.now(),signature:ASSINATURA};if(editingSupplier){const p=(editingSupplier.root==='suppliers'?'suppliers/':'fornecedores/')+editingSupplier.id;const payload=editingSupplier.root==='suppliers'?data:{nome:data.name,whatsapp:data.phone,tipos:data.types,obs:data.obs,ativo:true,atualizadoEm:new Date().toISOString()};db.ref(p).update(payload).then(()=>{clearSupplierForm();alert('Fornecedor atualizado.')});return}const id=uid('sup');db.ref('suppliers/'+id).set({id,...data,createdAt:Date.now()}).then(()=>clearSupplierForm())}
function editSupplier(root,id){const s=(root==='suppliers'?suppliers[id]:fornecedores[id])||{};editingSupplier={root,id};$('supName').value=s.name||s.nome||'';$('supPhone').value=s.phone||s.whatsapp||'';$('supTypes').value=(s.types||s.tipos||[]).join(', ');$('supObs').value=s.obs||'';showTab('fornecedores')}
function setSupplierActive(root,id,active){const p=(root==='suppliers'?'suppliers/':'fornecedores/')+id;const payload=root==='suppliers'?{active,updatedAt:Date.now()}:{ativo:active,atualizadoEm:new Date().toISOString()};db.ref(p).update(payload)}
function deleteSupplier(root,id){if(!confirm('Excluir definitivamente este fornecedor?'))return;db.ref((root==='suppliers'?'suppliers/':'fornecedores/')+id).remove()}
function normNew(id,q){const items=(q.items||[]).map((it,idx)=>({id:it.id||('item_'+idx),seq:it.seq||idx+1,oem:it.oem||it.codigoOriginal||'',altCode:it.altCode||'',desc:it.desc||it.descricaoOriginal||'',qty:Number(it.qty||it.quantidade||1),type:it.type||it.tipo||'geral',saleUnit:Number(it.saleUnit||it.valorUnitarioPlanilha||0),saleTotal:Number(it.saleTotal||it.totalLiquidoPlanilha||((it.saleUnit||0)*(it.qty||1))||0),raw:it}));return{id,source:'quotes',raw:q,number:q.number||q.numero||id,status:q.status||'open',createdAt:q.createdAt||q.updatedAt||0,vehicle:q.vehicle||q.veiculo||{},items,responses:q.responses||{},rawReplies:q.whatsappRawReplies||{}}}
function normOld(id,q){const items=Object.entries(q.pecas||{}).map(([pid,it],idx)=>({id:it.id||pid,seq:it.ordem||idx+1,oem:it.codigoOriginal||it.oem||'',altCode:'',desc:it.descricaoOriginal||it.desc||'',qty:Number(it.quantidade||it.qty||1),type:it.tipo||'geral',saleUnit:Number(it.valorUnitarioPlanilha||0),saleTotal:Number(it.totalLiquidoPlanilha||0),raw:it})).sort((a,b)=>(a.seq||0)-(b.seq||0));return{id,source:'cotacoes',raw:q,number:q.numero||q.number||id,status:q.status||'aberta',createdAt:q.criadaEm?Date.parse(q.criadaEm):0,vehicle:q.veiculo||{},items,responses:respostas[id]||q.responses||{},rawReplies:q.whatsappRawReplies||{}}}
function allQuotes(){const list=[];Object.entries(quotes||{}).forEach(([id,q])=>list.push(normNew(id,q||{})));Object.entries(cotacoes||{}).forEach(([id,q])=>list.push(normOld(id,q||{})));return list.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function responsesForItem(q,item){const rows=[];Object.entries(q.responses||{}).forEach(([sid,byItem])=>{const r=(byItem||{})[item.id];if(!r)return;const available=r.available!==undefined?r.available!==false:r.temDisponivel!==false;rows.push({supplierId:sid,supplierName:r.fornecedorNome||supplierName(sid,q),available,brand:r.brand||r.marca||'',brandCode:r.brandCode||r.codigoMarca||'',desc:r.desc||r.descricaoFornecedor||'',price:Number(r.price||r.precoUnitario||r.preco||0),availability:r.availability||r.disponibilidade||'',obs:r.obs||r.observacao||'',raw:r.raw||r.rawText||r.text||'',source:r.source||r.origem||'formulário',updatedAt:r.updatedAt||r.atualizadoEm||r.receivedAt||null})});rows.sort((a,b)=>{if(a.available!==b.available)return a.available?-1:1;return(a.price||999999999)-(b.price||999999999)});return rows}
function bestForItem(q,item){return responsesForItem(q,item).filter(r=>r.available&&r.price>0)[0]||null}
function renderAll(){const qs=allQuotes();$('kpiOpen').textContent=qs.filter(q=>statusOpen(q.status)).length;$('kpiClosed').textContent=qs.filter(q=>String(q.status).toLowerCase().includes('fech')||String(q.status).toLowerCase().includes('encerr')).length;$('kpiCanceled').textContent=qs.filter(q=>String(q.status).toLowerCase().includes('cancel')).length;$('kpiSupActive').textContent=supplierRows().filter(s=>s.active).length;$('kpiPrices').textContent=Object.keys(priceDb||{}).length;$('kpiQueue').textContent=arrObj(whatsappQueue).filter(x=>['pending','sending'].includes(x.status)).length;$('kpiUnmatched').textContent=Object.keys(auditUnmatched||{}).length;renderHome(qs);renderSuppliers();renderPrices();renderQuotes(qs);renderQueue();renderOrders();renderUnmatched();renderClientes();renderVeiculos();renderDebug(qs)}
function renderHome(qs){$('homeQuotes').innerHTML=qs.slice(0,6).map(q=>`<div class="quote"><b>${esc(q.number)}</b> — ${esc(q.source)} — ${esc(q.status)} — ${q.items.length} item(ns)</div>`).join('')||'<p class="muted">Sem cotações.</p>';$('homeOrders').innerHTML=arrObj(purchaseOrders).slice(0,5).map(o=>`<div class="quote"><b>${esc(o.supplierName||o.id)}</b> — ${money(o.total||0)}</div>`).join('')||'<p class="muted">Sem ordens.</p>';$('homePrices').innerHTML=arrObj(priceDb).slice(0,8).map(p=>`<div class="quote"><b>${esc(p.desc)}</b><br>${esc(p.brand||'')} ${money(p.price||0)}</div>`).join('')||'<p class="muted">Sem preços.</p>'}
function renderSuppliers(){const list=supplierRows();$('suppliersList').innerHTML=list.length?`<div class="tablewrap"><table><thead><tr><th>Nome</th><th>WhatsApp</th><th>Tipos</th><th>Obs.</th><th>Status</th><th>Origem</th><th>Ações</th></tr></thead><tbody>${list.map(s=>`<tr><td>${esc(s.name||s.id)}</td><td>${esc(s.phone||'')}</td><td>${esc((s.types||[]).join(', '))}</td><td>${esc(s.obs||'')}</td><td>${s.active?'<span class="ok">Ativo</span>':'<span class="bad">Inativo</span>'}</td><td>${s.root}</td><td><button class="light" onclick="editSupplier('${s.root}','${s.id}')">Editar</button>${s.active?`<button class="amber" onclick="setSupplierActive('${s.root}','${s.id}',false)">Desativar</button>`:`<button class="green" onclick="setSupplierActive('${s.root}','${s.id}',true)">Reativar</button>`}<button class="red" onclick="deleteSupplier('${s.root}','${s.id}')">Excluir</button><button class="light" onclick="alert('Histórico por fornecedor: ${esc(s.name||s.id)}')">Ver histórico</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Sem fornecedores.</p>';$('priceSupplier').innerHTML='<option value="">Selecione</option>'+list.map(s=>`<option value="${s.id}">${esc(s.name||s.id)}</option>`).join('')}
function savePrice(){const id=uid('price');db.ref('priceDb/'+id).set({supplierId:$('priceSupplier').value,oem:$('priceOem').value,desc:$('priceDesc').value,brand:$('priceBrand').value,brandCode:$('priceBrandCode').value,price:parseMoney($('priceValue').value),availability:$('priceAvailability').value,origin:$('priceOrigin').value,plate:$('pricePlate').value,chassi:$('priceChassi').value,quoteId:$('priceQuoteId').value,orderId:$('priceOrderId').value,niche:$('priceNiche').value||settings.niche||'oficina',obs:$('priceObs').value,updatedAt:Date.now(),signature:ASSINATURA}).then(()=>alert('Preço salvo.'))}
function renderPrices(){const q=String($('priceSearch')?.value||'').toLowerCase(),fn=String($('priceFilterNiche')?.value||'').toLowerCase(),fa=String($('priceFilterAvailability')?.value||'').toLowerCase();const list=arrObj(priceDb).filter(p=>(!q||[p.oem,p.desc,p.brand,p.brandCode,supplierName(p.supplierId),p.plate,p.chassi,p.niche,p.availability].join(' ').toLowerCase().includes(q))&&(!fn||String(p.niche||'').toLowerCase().includes(fn))&&(!fa||String(p.availability||'').toLowerCase().includes(fa)));$('priceList').innerHTML=list.length?`<div class="tablewrap"><table><thead><tr><th>Produto</th><th>Fornecedor</th><th>Marca</th><th>Preço</th><th>Disp.</th><th>Placa/Chassi</th><th>Ações</th></tr></thead><tbody>${list.map(p=>`<tr><td><b>${esc(p.desc)}</b><br>${esc(p.oem)}</td><td>${esc(supplierName(p.supplierId))}</td><td>${esc(p.brand||'-')} ${esc(p.brandCode||'')}</td><td>${money(p.price)}</td><td>${esc(p.availability||'-')}</td><td>${esc(p.plate||'')}<br>${esc(p.chassi||'')}</td><td><button class="light" onclick="addPriceToDraft('${p.id}')">Usar em cotação</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Sem preços.</p>'}
function addPriceToDraft(id){const p=priceDb[id];if(!p)return;draftItems.push({id:uid('item'),seq:draftItems.length+1,oem:p.oem||'',altCode:p.brandCode||'',desc:p.desc||'',qty:1,type:p.niche||'geral',saleUnit:Number(p.price||0),saleTotal:Number(p.price||0),obs:'Banco de preços'});renderDraft();showTab('novo')}
function renderQuotes(qs){$('quotesList').innerHTML=qs.length?qs.map(q=>{const answered=q.items.filter(it=>!!bestForItem(q,it)).length;let lucro=0;q.items.forEach(it=>{const b=bestForItem(q,it);if(b)lucro+=Number(it.saleTotal||0)-(b.price*Number(it.qty||1))});const v=q.vehicle||{};const mode=uiState.openPanels[`${q.source}_${q.id}`]||'';return`<div class="quote ${String(q.status).toLowerCase().includes('cancel')?'canceled':(statusOpen(q.status)?'':'closed')}"><h3>${esc(q.number)} <span class="pill">${esc(q.source)}</span> <span class="pill">${esc(q.status)}</span></h3><p class="muted">${esc([v.marca||v.brand,v.modelo||v.model,v.ano||v.year,v.placa||v.plate,v.chassi].filter(Boolean).join(' '))} — ${q.items.length} item(ns) — respondidos ${answered}/${q.items.length}</p><p><b>Lucro estimado:</b> <span class="${lucro>=0?'ok':'bad'}">${money(lucro)}</span></p><div class="row"><button onclick="setOpenPanel('${q.source}','${q.id}','comparison')">Comparar respostas</button><button class="light" onclick="setOpenPanel('${q.source}','${q.id}','items')">Ver peças</button><button class="light" onclick="setOpenPanel('${q.source}','${q.id}','raw')">Respostas WhatsApp</button><button class="light" onclick="setOpenPanel('${q.source}','${q.id}','send')">Enviar fornecedores</button><button class="green" onclick="generateOC('${q.source}','${q.id}')">Gerar OC</button><button class="light" onclick="editQuote('${q.source}','${q.id}')">Editar</button>${statusOpen(q.status)?`<button class="amber" onclick="setQuoteStatus('${q.source}','${q.id}','fechada')">Encerrar</button><button class="red" onclick="setQuoteStatus('${q.source}','${q.id}','cancelada')">Cancelar</button>`:`<button class="green" onclick="setQuoteStatus('${q.source}','${q.id}','aberta')">Reabrir</button>`}<button class="red" onclick="deleteQuote('${q.source}','${q.id}')">Excluir</button><button class="light" onclick="exportComparativo('${q.source}','${q.id}')">Exportar comparativo</button></div>${renderQuoteDetail(q,mode)}</div>`}).join(''):'<p class="muted">Nenhuma cotação criada.</p>'}
function setOpenPanel(source,id,mode){uiState.openPanels[`${source}_${id}`]=mode;renderQuotes(allQuotes())}
function renderQuoteDetail(q,mode){if(!mode)return'';if(mode==='comparison')return comparisonHTML(q);if(mode==='items')return itemsHTML(q);if(mode==='raw')return rawHTML(q);if(mode==='send')return sendHTML(q);return''}
function comparisonHTML(q){let html=`<div class="panel"><h3>Comparação completa</h3>`;q.items.forEach(it=>{const rows=responsesForItem(q,it),qty=Number(it.qty||1);html+=`<div class="piecebox"><h3>${esc(it.seq)}. ${esc(it.desc)}</h3><span class="pill">Código: ${esc(it.oem)}</span><span class="pill">Qtd: ${qty}</span>`;if(!rows.length)html+=`<p class="bad">Sem resposta.</p>`;else{html+=`<div class="tablewrap"><table><thead><tr><th>Fornecedor</th><th>Status</th><th>Marca</th><th>Cód. marca</th><th>Descrição</th><th>Unit.</th><th>Total</th><th>Prazo</th><th>Obs./bruto</th></tr></thead><tbody>`;rows.forEach(r=>{const price=Number(r.price||0);html+=`<tr><td><b>${esc(r.supplierName)}</b><br><span class="muted">${esc(r.source)}</span></td><td>${r.available?'<span class="ok">Tem</span>':'<span class="bad">Não tem</span>'}</td><td>${esc(r.brand||'-')}</td><td>${esc(r.brandCode||'-')}</td><td>${esc(r.desc||'-')}</td><td>${price?money(price):'-'}</td><td>${price?money(price*qty):'-'}</td><td>${esc(r.availability||'-')}</td><td>${esc(r.obs||'-')}${r.raw?`<br><span class="muted">Bruto: ${esc(r.raw)}</span>`:''}</td></tr>`});html+=`</tbody></table></div>`}html+=`</div>`});return html+`<p class="muted small">${ASSINATURA}</p></div>`}
function itemsHTML(q){let html=`<div class="panel"><h3>Peças</h3><div class="tablewrap"><table><thead><tr><th>#</th><th>Código</th><th>Descrição</th><th>Qtd</th><th>Venda/base</th><th>Tipo</th></tr></thead><tbody>`;q.items.forEach(it=>html+=`<tr><td>${it.seq}</td><td>${esc(it.oem)}</td><td>${esc(it.desc)}</td><td>${it.qty}</td><td>${money(it.saleTotal)}</td><td>${esc(it.type)}</td></tr>`);return html+`</tbody></table></div></div>`}
function rawHTML(q){const raws=Object.entries(q.rawReplies||{}).sort((a,b)=>(b[1].receivedAt||0)-(a[1].receivedAt||0));let html=`<div class="panel"><h3>Respostas diretas no WhatsApp</h3>`;if(!raws.length)html+=`<p class="muted">Nenhuma resposta direta registrada.</p>`;raws.forEach(([rid,r])=>html+=`<div class="quote"><b>${esc(r.supplierName||supplierName(r.supplierId,q))}</b><br><span class="muted">${r.receivedAt?new Date(r.receivedAt).toLocaleString('pt-BR'):''} — ${esc(r.parseStatus||'')}</span><pre>${esc(r.text||'')}</pre></div>`);return html+`</div>`}
function sendHTML(q){const list=supplierRows();const key=`${q.source}_${q.id}`;uiState.selectedSuppliers[key]=uiState.selectedSuppliers[key]||{};let html=`<div class="panel"><h3>Enviar para fornecedores</h3><div class="row"><button class="light" onclick="selectAllSend('${q.source}','${q.id}')">Selecionar todos</button><button class="light" onclick="clearSend('${q.source}','${q.id}')">Limpar seleção</button><button onclick="enqueueSelected('${q.source}','${q.id}')">Enviar selecionados com robô</button></div><div class="grid">`;list.forEach(s=>{const sk=`${s.root}:${s.id}`;html+=`<label class="checkboxCard"><input type="checkbox" ${uiState.selectedSuppliers[key][sk]?'checked':''} onchange="toggleSend('${q.source}','${q.id}','${sk}',this.checked)"> <b>${esc(s.name||s.id)}</b><br><span class="muted">${esc(s.phone||'')}</span></label>`});return html+`</div></div>`}
function toggleSend(source,id,sk,checked){const key=`${source}_${id}`;uiState.selectedSuppliers[key]=uiState.selectedSuppliers[key]||{};uiState.selectedSuppliers[key][sk]=checked}
function selectAllSend(source,id){const key=`${source}_${id}`;uiState.selectedSuppliers[key]={};supplierRows().forEach(s=>uiState.selectedSuppliers[key][`${s.root}:${s.id}`]=true);setOpenPanel(source,id,'send')}
function clearSend(source,id){uiState.selectedSuppliers[`${source}_${id}`]={};setOpenPanel(source,id,'send')}
function getQuote(source,id){return allQuotes().find(q=>q.source===source&&q.id===id)}
function quoteLink(source,id,sid){return location.origin+location.pathname.replace(/index\.html.*$/,'')+`fornecedor.html?source=${encodeURIComponent(source)}&q=${encodeURIComponent(id)}&s=${encodeURIComponent(sid)}`}
function buildMessage(q,sid,s){const link=quoteLink(q.source,q.id,sid);return (settings.messageTemplate||DEFAULT_MSG).replaceAll('{fornecedor}',s.name||s.nome||'Fornecedor').replaceAll('{estabelecimento}',settings.name||'Estabelecimento').replaceAll('{cotacao}',q.number||q.id).replaceAll('{veiculo}',q.vehicle?.modelo||q.vehicle?.model||'').replaceAll('{placa}',q.vehicle?.placa||q.vehicle?.plate||'').replaceAll('{chassi}',q.vehicle?.chassi||'').replaceAll('{qtd}',q.items.length).replaceAll('{link}',link).replaceAll('{assinatura}',ASSINATURA)}
function enqueueSelected(source,id){const q=getQuote(source,id);if(!q)return;const key=`${source}_${id}`;const all={};supplierRows().forEach(s=>all[`${s.root}:${s.id}`]=s);const chosen=Object.keys(uiState.selectedSuppliers[key]||{}).filter(k=>uiState.selectedSuppliers[key][k]).map(k=>all[k]).filter(Boolean);if(!chosen.length)return alert('Selecione fornecedores.');const updates={};chosen.forEach(s=>{const wa=uid('wa');updates[`whatsappQueue/${wa}`]={quoteId:q.id,quoteSource:q.source,quoteNumber:q.number,supplierId:s.id,supplierName:s.name,phone:phoneBR(s.phone),message:buildMessage(q,s.id,s),status:'pending',createdAt:Date.now(),signature:ASSINATURA}});db.ref().update(updates).then(()=>alert(`${chosen.length} mensagem(ns) na fila.`))}
function setQuoteStatus(source,id,status){db.ref((source==='quotes'?`quotes/${id}/status`:`cotacoes/${id}/status`)).set(status)}
function deleteQuote(source,id){if(!confirm('Excluir definitivamente esta cotação e suas respostas?'))return;const updates={};updates[source==='quotes'?`quotes/${id}`:`cotacoes/${id}`]=null;if(source==='cotacoes')updates[`respostas/${id}`]=null;db.ref().update(updates)}
function editQuote(source,id){const q=getQuote(source,id);if(!q)return;editing={source,id};$('quoteFormTitle').textContent='Editando cotação '+q.number;$('quoteNumber').value=q.number;const v=q.vehicle||{};$('vehCustomer').value=v.customer||v.cliente||'';$('vehBrand').value=v.brand||v.marca||'';$('vehModel').value=v.model||v.modelo||'';$('vehYear').value=v.year||v.ano||'';$('vehPlate').value=v.plate||v.placa||'';$('vehChassi').value=v.chassi||'';$('vehKm').value=v.km||'';$('vehPrefix').value=v.prefix||v.prefixo||'';$('vehObs').value=v.obs||'';draftItems=q.items.map((it,idx)=>({...it,seq:idx+1}));renderDraft();showTab('novo')}
function generateOC(source,id){const q=getQuote(source,id);if(!q)return;const wins=[];q.items.forEach(it=>{const b=bestForItem(q,it);if(b)wins.push({it,b})});if(!wins.length)return alert('Nenhuma resposta válida para gerar OC.');const grouped={};wins.forEach(w=>{if(!grouped[w.b.supplierId])grouped[w.b.supplierId]=[];grouped[w.b.supplierId].push(w)});const updates={};Object.entries(grouped).forEach(([sid,arr])=>{const ocid=uid('oc'),total=arr.reduce((s,w)=>s+w.b.price*Number(w.it.qty||1),0),profit=arr.reduce((s,w)=>s+(Number(w.it.saleTotal||0)-w.b.price*Number(w.it.qty||1)),0);updates[`purchaseOrders/${ocid}`]={id:ocid,quoteId:id,quoteSource:source,quoteNumber:q.number,supplierId:sid,supplierName:supplierName(sid,q),total,profit,status:'aberta',createdAt:Date.now(),items:arr.map(w=>({oem:w.it.oem,desc:w.it.desc,qty:w.it.qty,brand:w.b.brand,brandCode:w.b.brandCode,priceUnit:w.b.price,total:w.b.price*Number(w.it.qty||1),availability:w.b.availability,obs:w.b.obs})),signature:ASSINATURA}});db.ref().update(updates).then(()=>{alert('Ordem de compra gerada.');showTab('compras')})}
function exportComparativo(source,id){alert('Exportação XLSX do comparativo: funcionalidade preparada para próxima etapa.')}
function renderQueue(){const list=arrObj(whatsappQueue).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('robotQueue').innerHTML=list.length?`<div class="tablewrap"><table><thead><tr><th>Status</th><th>Fornecedor</th><th>Telefone</th><th>Mensagem</th></tr></thead><tbody>${list.map(x=>`<tr><td>${esc(x.status)}</td><td>${esc(x.supplierName||supplierName(x.supplierId))}</td><td>${esc(x.phone||'')}</td><td>${esc(String(x.message||'').slice(0,160))}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Fila vazia.</p>';renderUnmatched()}
function renderUnmatched(){const list=arrObj(auditUnmatched).sort((a,b)=>(b.receivedAt||0)-(a.receivedAt||0));const html=list.length?list.map(x=>`<div class="unmatched"><b>Remetente:</b> ${esc(x.rawId||x.remetente||x.from)}<br><b>Recebido:</b> ${x.receivedAt?new Date(x.receivedAt).toLocaleString('pt-BR'):''}<pre>${esc(x.text||'')}</pre><div class="row"><select id="waSup_${x.id}"><option value="">Fornecedor...</option>${supplierRows().map(s=>`<option value="${s.id}">${esc(s.name)} (${esc(s.phone)})</option>`).join('')}</select><button class="amber" onclick="vincularWhatsapp('${x.id}','${esc(x.rawId||x.remetente||x.from)}')">Vincular</button><button class="red" onclick="db.ref('audit/unmatchedWhatsapp/${x.id}').remove()">Excluir</button></div></div>`).join(''):'<p class="muted">Nenhuma resposta não vinculada.</p>';$('unmatchedList').innerHTML=html;$('unmatchedWhatsappFull').innerHTML=html}
function vincularWhatsapp(logId,rawId){const sid=$(`waSup_${logId}`).value;if(!sid)return alert('Selecione fornecedor.');db.ref(`whatsappContacts/${rawId}`).set({supplierId:sid,mappedAt:Date.now(),signature:ASSINATURA}).then(()=>db.ref(`audit/unmatchedWhatsapp/${logId}`).remove())}
function renderOrders(){const list=[...arrObj(purchaseOrders),...arrObj(ordensCompra)];$('ordersList').innerHTML=list.length?list.map(o=>`<div class="quote"><b>${esc(o.supplierName||o.fornecedorNome||o.id)}</b><br>Total: ${money(o.total||o.totalCompra||0)} | Lucro: ${money(o.profit||o.lucroTotal||0)}<br><button class="light" onclick="window.print()">Imprimir</button><button class="amber" onclick="alert('Marcado como comprada')">Marcar comprada</button><button class="green" onclick="alert('Marcado como recebida')">Marcar recebida</button></div>`).join(''):'<p class="muted">Nenhuma ordem de compra.</p>'}
function renderDebug(qs){$('debugBox').innerHTML=`<ul><li>Firebase conectado: ${db?'sim':'não'}</li><li>Auth conectado: ${firebase.auth?'sim':'não'}</li><li>Usuário logado: ${currentUser?currentUser.email:'não'}</li><li>Versão: final-profissional</li><li>URL atual: ${location.href}</li><li>Nicho ativo: ${settings.niche||''}</li><li>Tema ativo: ${settings.theme||localStorage.getItem('valorIA_theme')||'light'}</li><li>settings: ${Object.keys(settings||{}).length}</li><li>clientSetup: ${Object.keys(clientSetup||{}).length}</li><li>quotes: ${Object.keys(quotes||{}).length}</li><li>cotacoes: ${Object.keys(cotacoes||{}).length}</li><li>respostas: ${Object.keys(respostas||{}).length}</li><li>suppliers: ${Object.keys(suppliers||{}).length}</li><li>fornecedores: ${Object.keys(fornecedores||{}).length}</li><li>priceDb: ${Object.keys(priceDb||{}).length}</li><li>whatsappQueue: ${Object.keys(whatsappQueue||{}).length}</li><li>audit/unmatchedWhatsapp: ${Object.keys(auditUnmatched||{}).length}</li><li>purchaseOrders: ${Object.keys(purchaseOrders||{}).length}</li><li>ordensCompra: ${Object.keys(ordensCompra||{}).length}</li><li>Total normalizado: ${qs.length}</li></ul>`}
function saveCliente(){const id=editingCliente||uid('cli');db.ref('oficina/clientes/'+id).update({id,nome:$('cliNome').value,telefone:$('cliTel').value,documento:$('cliDoc').value,empresa:$('cliEmpresa').value,responsavel:$('cliResp').value,email:$('cliEmail').value,obs:$('cliObs').value,updatedAt:Date.now(),signature:ASSINATURA}).then(()=>clearClienteForm())}
function clearClienteForm(){editingCliente=null;['cliNome','cliTel','cliDoc','cliEmpresa','cliResp','cliEmail','cliObs'].forEach(i=>$(i).value='')}
function renderClientes(){const q=($('cliSearch')?.value||'').toLowerCase();const list=arrObj(oficinaClientes).filter(c=>!q||[c.nome,c.telefone,c.documento,c.empresa,c.responsavel,c.email].join(' ').toLowerCase().includes(q));$('clientesList').innerHTML=list.length?`<div class="tablewrap"><table><thead><tr><th>Nome</th><th>Telefone</th><th>Doc.</th><th>Empresa</th><th>Ações</th></tr></thead><tbody>${list.map(c=>`<tr><td>${esc(c.nome)}</td><td>${esc(c.telefone)}</td><td>${esc(c.documento)}</td><td>${esc(c.empresa)}</td><td><button class="light" onclick="editCliente('${c.id}')">Editar</button><button class="red" onclick="deleteCliente('${c.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Nenhum cliente.</p>'}
function editCliente(id){const c=oficinaClientes[id]||{};editingCliente=id;$('cliNome').value=c.nome||'';$('cliTel').value=c.telefone||'';$('cliDoc').value=c.documento||'';$('cliEmpresa').value=c.empresa||'';$('cliResp').value=c.responsavel||'';$('cliEmail').value=c.email||'';$('cliObs').value=c.obs||'';showTab('clientes')}
function deleteCliente(id){if(confirm('Excluir cliente?'))db.ref('oficina/clientes/'+id).remove()}
function saveVeiculo(){const id=editingVeiculo||uid('vei');db.ref('oficina/veiculos/'+id).update({id,placa:$('veiPlaca').value,chassi:$('veiChassi').value,marca:$('veiMarca').value,modelo:$('veiModelo').value,ano:$('veiAno').value,km:$('veiKm').value,prefixo:$('veiPrefixo').value,cliente:$('veiCliente').value,obs:$('veiObs').value,updatedAt:Date.now(),signature:ASSINATURA}).then(()=>clearVeiculoForm())}
function clearVeiculoForm(){editingVeiculo=null;['veiPlaca','veiChassi','veiMarca','veiModelo','veiAno','veiKm','veiPrefixo','veiCliente','veiObs'].forEach(i=>$(i).value='')}
function renderVeiculos(){const q=($('veiSearch')?.value||'').toLowerCase();const list=arrObj(oficinaVeiculos).filter(v=>!q||[v.placa,v.chassi,v.marca,v.modelo,v.ano,v.prefixo,v.cliente].join(' ').toLowerCase().includes(q));$('veiculosList').innerHTML=list.length?`<div class="tablewrap"><table><thead><tr><th>Placa</th><th>Chassi</th><th>Veículo</th><th>Cliente</th><th>Ações</th></tr></thead><tbody>${list.map(v=>`<tr><td>${esc(v.placa)}</td><td>${esc(v.chassi)}</td><td>${esc([v.marca,v.modelo,v.ano].filter(Boolean).join(' '))}</td><td>${esc(v.cliente)}</td><td><button class="green" onclick="useVeiculo('${v.id}')">Usar</button><button class="light" onclick="editVeiculo('${v.id}')">Editar</button><button class="red" onclick="deleteVeiculo('${v.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Nenhum veículo.</p>'}
function editVeiculo(id){const v=oficinaVeiculos[id]||{};editingVeiculo=id;$('veiPlaca').value=v.placa||'';$('veiChassi').value=v.chassi||'';$('veiMarca').value=v.marca||'';$('veiModelo').value=v.modelo||'';$('veiAno').value=v.ano||'';$('veiKm').value=v.km||'';$('veiPrefixo').value=v.prefixo||'';$('veiCliente').value=v.cliente||'';$('veiObs').value=v.obs||'';showTab('veiculos')}
function useVeiculo(id){const v=oficinaVeiculos[id]||{};$('vehPlate').value=v.placa||'';$('vehChassi').value=v.chassi||'';$('vehBrand').value=v.marca||'';$('vehModel').value=v.modelo||'';$('vehYear').value=v.ano||'';$('vehKm').value=v.km||'';$('vehPrefix').value=v.prefixo||'';$('vehCustomer').value=v.cliente||'';showTab('novo');searchVehicleHistory()}
function deleteVeiculo(id){if(confirm('Excluir veículo?'))db.ref('oficina/veiculos/'+id).remove()}
function searchVehicleHistory(){const placa=($('vehPlate')?.value||'').toLowerCase(),chassi=($('vehChassi')?.value||'').toLowerCase(),cliente=($('vehCustomer')?.value||'').toLowerCase();if(!placa&&!chassi&&!cliente){$('vehicleHistoryBox').innerHTML='';return}const matches=allQuotes().filter(q=>{const v=q.vehicle||{};return(placa&&String(v.placa||v.plate||'').toLowerCase().includes(placa))||(chassi&&String(v.chassi||'').toLowerCase().includes(chassi))||(cliente&&String(v.customer||v.cliente||'').toLowerCase().includes(cliente))});$('vehicleHistoryBox').innerHTML=matches.length?`<div class="panel"><h3>Histórico encontrado</h3>${matches.slice(0,5).map(q=>`<div class="quote"><b>${esc(q.number)}</b> — ${q.items.length} itens<br>${q.items.slice(0,6).map(i=>esc(i.desc)).join('<br>')}</div>`).join('')}</div>`:''}
function addDraftItem(){const desc=$('itemDesc').value.trim();if(!desc)return alert('Descrição obrigatória.');const qty=parseMoney($('itemQty').value)||1,unit=parseMoney($('itemSale').value);draftItems.push({id:uid('item'),seq:draftItems.length+1,oem:$('itemOem').value.trim(),altCode:$('itemAlt').value.trim(),desc,qty,type:$('itemType').value.trim()||'geral',saleUnit:unit,saleTotal:unit*qty,obs:$('itemObs')?.value||''});renderDraft();['itemOem','itemAlt','itemDesc','itemSale','itemType'].forEach(i=>$(i).value='');$('itemQty').value='1';if($('itemObs'))$('itemObs').value=''}
function renderDraft(){$('draftItems').innerHTML=draftItems.length?`<div class="tablewrap"><table><thead><tr><th>#</th><th>Código</th><th>Descrição</th><th>Qtd</th><th>Total</th></tr></thead><tbody>${draftItems.map((i,idx)=>`<tr><td>${idx+1}</td><td>${esc(i.oem)}</td><td>${esc(i.desc)}</td><td>${i.qty}</td><td>${money(i.saleTotal)}</td></tr>`).join('')}</tbody></table></div>`:''}
function clearQuoteForm(){editing=null;draftItems=[];['quoteNumber','vehCustomer','vehBrand','vehModel','vehYear','vehPlate','vehChassi','vehKm','vehPrefix','vehObs','quoteNiche','quoteStatus','itemOem','itemAlt','itemDesc','itemSale','itemType','itemObs'].forEach(i=>{if($(i))$(i).value=''});$('itemQty').value='1';$('quoteFormTitle').textContent='Novo orçamento / cotação';renderDraft()}
function saveQuote(){if(!draftItems.length)return alert('Adicione peças.');const vehicle={customer:$('vehCustomer').value,brand:$('vehBrand').value,model:$('vehModel').value,year:$('vehYear').value,plate:$('vehPlate').value,chassi:$('vehChassi').value,km:$('vehKm').value,prefix:$('vehPrefix').value,obs:$('vehObs').value};if(editing&&editing.source==='cotacoes'){const pecas={};draftItems.forEach((it,idx)=>pecas[it.id||('p'+idx)]={id:it.id||('p'+idx),ordem:idx+1,codigoOriginal:it.oem,descricaoOriginal:it.desc,quantidade:it.qty,tipo:it.type,totalLiquidoPlanilha:it.saleTotal,valorUnitarioPlanilha:it.saleUnit});db.ref('cotacoes/'+editing.id).update({numero:$('quoteNumber').value,status:'aberta',veiculo:{marca:vehicle.brand,modelo:vehicle.model,ano:vehicle.year,placa:vehicle.plate,chassi:vehicle.chassi,km:vehicle.km,prefixo:vehicle.prefix},pecas,totalPecas:draftItems.length}).then(()=>{clearQuoteForm();showTab('cotacoes')});return}const id=editing?.id||uid('quote');const payload={id,number:$('quoteNumber').value.trim()||id,status:$('quoteStatus').value||'open',vehicle,niche:$('quoteNiche').value||settings.niche||'oficina',items:draftItems.map((x,i)=>({...x,seq:i+1})),updatedAt:Date.now(),signature:ASSINATURA};if(!editing)payload.createdAt=Date.now();db.ref('quotes/'+id).update(payload).then(()=>{clearQuoteForm();showTab('cotacoes');alert('Cotação salva.')})}
function saveDraftQuote(){const old=$('quoteStatus').value;$('quoteStatus').value='rascunho';saveQuote();$('quoteStatus').value=old}
function importXlsx(){const file=$('fileXlsx').files[0];if(!file)return alert('Escolha a planilha.');const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(new Uint8Array(e.target.result),{type:'array'});let rows=[];wb.SheetNames.forEach(n=>rows.push(...XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:''})));let parsed=[];rows.forEach((r,idx)=>{let cells=r.map(x=>String(x||'').trim());let text=cells.join(' ').toUpperCase();if(text.includes('SERVIÇO')||text.includes('SERVICO')||text.includes('MÃO DE OBRA'))return;if(!(text.includes('PEÇA')||text.includes('PECA')||text.includes('COD')||text.includes('GRADE')))return;let desc=cells.find(c=>c.length>6&&!/PE[ÇC]A|COD|VALOR|QTD|DESCRI|GRADE/i.test(c))||'';if(!desc||desc.toUpperCase()==='DESCRIÇÃO')return;let code=cells.find(c=>/[A-Z0-9]{5,}/i.test(c)&&! /PE[ÇC]A|COD|DESCRI/i.test(c))||'sem oem';let nums=cells.map(parseMoney).filter(n=>n>0);let qty=nums.find(n=>n>0&&n<1000)||1;let total=nums[nums.length-1]||0;parsed.push({id:uid('item'),seq:draftItems.length+parsed.length+1,oem:code,altCode:'',desc,qty,type:'geral',saleUnit:total&&qty?total/qty:0,saleTotal:total,origemLinha:idx+1})});draftItems.push(...parsed);renderDraft();alert(parsed.length+' peça(s) importadas.')};reader.readAsArrayBuffer(file)}
window.addEventListener('load',init);
